# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: event <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/06/04 09:40:35 by event             #+#    #+#              #
#    Updated: 2019/06/04 09:45:11 by event            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	@echo "Compiling Magaphone"
	@clang++ -Wall -Wextra -Werror -o magaphone megaphone.cpp

clean:
	@echo "removing Magaphone"
	@rm magaphone
